<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SPEAKERS_category</name>
   <tag></tag>
   <elementGuidId>663e6411-105c-48a5-9787-a8b61c6b7d5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='category'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af69495e-f2cf-4fe2-a0d8-4887b8ef3174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>284eeb3a-7a95-41bd-8c10-1effa803b9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7e78257e-84a8-4b10-98ab-bb074e42a092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>categ.checked</value>
      <webElementGuid>3721313f-ce3d-470e-8fee-5b5f2b330583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>includeProducts(categ.id, 'CATEGORIES')</value>
      <webElementGuid>ea27e8fa-beb6-45a0-b4b1-075ea5d19880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-dirty ng-valid-parse</value>
      <webElementGuid>8547b949-7131-43a8-b322-c607e22ded99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobileSlide&quot;)/ul[1]/li[@class=&quot;ng-scope&quot;]/div[@class=&quot;option&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;fill&quot;]/input[@class=&quot;ng-untouched ng-valid ng-dirty ng-valid-parse&quot;]</value>
      <webElementGuid>1ea7720d-9274-4fa0-93f4-fb9b2cc397c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='category'])[5]</value>
      <webElementGuid>8d6da0b9-1a58-48a9-aa11-6820cf4acdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li/div/div[5]/div/input</value>
      <webElementGuid>e771235c-c028-41d3-b4f2-a676defb5d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>f51ee312-07a1-4cca-9126-2e9d9f293d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'category' and @type = 'checkbox']</value>
      <webElementGuid>ad642089-2946-4108-99e7-42841cafe1ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
