<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_laptop_name</name>
   <tag></tag>
   <elementGuidId>dd41a885-8750-4def-a408-a4a00eb6f348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>c8a894ce-46f5-4193-aee3-4be2567b760b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;Description&quot;]/h1</value>
      <webElementGuid>ac43c33c-7080-4169-ad6d-48074a3b4266</webElementGuid>
   </webElementProperties>
</WebElementEntity>
