<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PRICE_noUi-handle noUi-handle-upper</name>
   <tag></tag>
   <elementGuidId>46363486-93bf-4fc1-8dee-b543e568ea77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slider']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.noUi-handle.noUi-handle-upper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a6c78c5e-1ca7-4a01-b719-51ed087372b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noUi-handle noUi-handle-upper</value>
      <webElementGuid>c7551138-71cb-4fbd-8efe-2b327c6f7e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slider&quot;)/div[@class=&quot;noUi-base&quot;]/div[@class=&quot;noUi-origin noUi-background&quot;]/div[@class=&quot;noUi-handle noUi-handle-upper&quot;]</value>
      <webElementGuid>55753b50-a9bf-4e08-b07a-6f964697333b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slider']/div/div[2]/div</value>
      <webElementGuid>da3dd5cb-06a4-40e7-a8af-433c4ba3055c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div</value>
      <webElementGuid>bc4c09bb-e430-49ca-8f6b-3986cecc76ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
